/**
 * BotStrategies.js — Re-export portal facade aggregating all strategy engines and helpers (Phase 4b)
 */

import { BUILTIN_BOTS, BUILTIN_STRATEGIES } from './BotLoader.js';
import {
  DEFAULT_WEIGHTS,
  getBoardState,
  getPossibleActions,
  applyLightweightAction,
  getPieceValue,
  calculateMobility,
  calculateCenterControl,
  calculateMirrorUtilization,
  getPrimaryTarget,
  computeSafetySteps,
  getReverseFiringCells,
  bfsToNearestFiringCell,
  evaluateMediumAttacker,
  evaluateBoardAttacker,
  get2d6CumulativeProbability,
  get2d6ExactProbability,
  findOpponentMinScore,
  findBestActionSequenceExpectiminimax,
  evaluateMediumDefender,
  evaluateBoardDefender,
  findBestActionSequence,
  getCautiousness,
  getDefenderCautiousness,
  planReverseAttack,
  generatePossibilityWeb,
  generateThreatMap,
  generateExpectiminimaxThreatMap,
  classifyMove,
  getChallengeRecommendation,
  getPieceThreatLevels,
  classifyPlay,
  formatActionText,
  getEngineLines,
  getBoardAnalysis,
  genericSetupAction
} from './BotHelpers.js';

// Custom dynamic strategy registry
export const CUSTOM_STRATEGIES = {};
export const CUSTOM_BOTS_METADATA = {};

export {
  BUILTIN_BOTS,
  BUILTIN_STRATEGIES,
  DEFAULT_WEIGHTS,
  getBoardState,
  getPossibleActions,
  applyLightweightAction,
  getPieceValue,
  calculateMobility,
  calculateCenterControl,
  calculateMirrorUtilization,
  getPrimaryTarget,
  computeSafetySteps,
  getReverseFiringCells,
  bfsToNearestFiringCell,
  evaluateMediumAttacker,
  evaluateBoardAttacker,
  get2d6CumulativeProbability,
  get2d6ExactProbability,
  findOpponentMinScore,
  findBestActionSequenceExpectiminimax,
  evaluateMediumDefender,
  evaluateBoardDefender,
  findBestActionSequence,
  getCautiousness,
  getDefenderCautiousness,
  planReverseAttack,
  generatePossibilityWeb,
  generateThreatMap,
  generateExpectiminimaxThreatMap,
  classifyMove,
  getChallengeRecommendation,
  getPieceThreatLevels,
  classifyPlay,
  formatActionText,
  getEngineLines,
  getBoardAnalysis,
  genericSetupAction
};
